class_path: pytorch_lightning.callbacks.model_checkpoint.ModelCheckpoint
init_args:
  dirpath: CHECKPOINT_DIR
  filename: CHECKPOINT_FILENAME
  monitor: val_kendall
  verbose: True
  save_last: False
  save_top_k: 200
  mode: max
  auto_insert_metric_name: True
  save_weights_only: True
  every_n_train_steps: 10000
  train_time_interval: null
  every_n_epochs: null
  save_on_train_epoch_end: null